Idempot middleware
autoscalerhq/Autoscaler pull request #13
Opened 2024-08-22 02:53 UTC by EdWrld

- Created Idempotency middleware
- Simple Util functions for nats
- Simple util functions for std http to reduce some boiler plate (http.Post doesn't let you pass in your own headers...)
- Created tests for idempotency middleware: TestPostTwoOfTheSame, TestConcurrentRequests, TestPostNewIdempotentItem

2024-08-22 13:54 UTC, jasekiw requested changes

2024-08-22 13:54 UTC, jasekiw commented on services/api/middleware/idempotent.go
> +						return c.JSON(http.StatusInternalServerError, Message{Body: "Internal Server Error, please try again later"})
Doesn't echo just let your return the error and it shows an internal server error and logs it to our error monitoring software?

2024-08-22 13:58 UTC, Cliftonz requested changes

2024-08-22 13:58 UTC, Cliftonz commented on services/api/main.go
> +	// TODO this is broken and needs to be fixed Error : Unable to init provider initialization failed: grpc connection establishment failed
My wander is did you spin the flagd server up from the docker compose file when you merged it

2024-08-22 13:58 UTC, Cliftonz commented on services/api/main.go
> +	e.Use(appmiddleware.IdempotencyMiddleware(kv, idempotentCtx))
This should come after these as they count the number of requests for load shedding and augments them
```
e.Use(appmiddleware.RequestCounterMiddleware)
e.Use(appmiddleware.AddRouteToCTXMiddleware) 
	// If load is too high, fail before we process anything else. this may need to be moved after logging
	e.Use(echo.WrapMiddleware(loadshedhttp.NewHandlerMiddleware(appmiddleware.CreateShedder(), loadshedhttp.HandlerOptionCallback(&appmiddleware.RejectionHandler{}))))
```

This way even if the request is idempotent if the server is overloaded we can fail fast and shed. 
From my research we want to follow:
- load shedding
- rate limiting
- idempotency
- other middleware
- app logic

2024-08-22 13:58 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +	IdempotencyKey = "Idempotency-Key"
Is this the http request header key?

2024-08-22 13:58 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +//TODO 422 Unprocessable Entity missing case If there's an attempt to reuse an idempotency key with a different request payload.
This needs to be added before we merge this, as the 422 error is the core piece of idempotency to ensure consistency

2024-08-22 13:58 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +	return func(next echo.HandlerFunc) echo.HandlerFunc {
I also think you have double tab enabled here, this is alot of tabs per each line

2024-08-22 13:58 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +					resp, respErr := json.Marshal(
What hashing algorithm are we using for to store the request in the kv store?

2024-08-22 13:58 UTC, Cliftonz commented on services/api/util/http.go
> +func Post(requestUrl string, body interface{}, header http.Header, ctx context.Context) (*http.Response, http.Header, error) {
Is this the extention to the http library?

2024-08-22 20:51 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +					resp, respErr := json.Marshal(
Yes, you should be hashing the body of the request and using that as your key in the kv store. This is bc nats kv limits the key size to be 512 bytes (redis limit is 512mb which is huge), we do not store sensitive data in the cache, and so we can easily see if it has already been used.

You should use [blake2b512](https://pkg.go.dev/golang.org/x/crypto/blake2b)  which is built into the [standard library](https://pkg.go.dev/crypto#Hash) for the hashing function as it's faster and more collision resistant than other options like sha256.

2024-08-22 20:57 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +
No, both the payload and the idempotency key have to match for us to return the cached result. 
Otherwise, we will return a 409 when either the above does not match or the request is currently processing as described here in the [idempotency http draft in section 2.7](https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/)

I made a comment above about how we should be hashing the body and not storing the body as a key.

2024-08-22 21:03 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +//TODO 422 Unprocessable Entity missing case If there's an attempt to reuse an idempotency key with a different request payload.
In the idempotency http spec section 2.7 describes the following scenario for when to use a 422 vs a 409
https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/

basically 422 if the hash does not match the idempotency key and 409 if the request is processing.

The state machine would be initiated, proccessing, completed (w/ body cached).

2024-08-23 00:44 UTC, EdWrld commented on services/api/util/http.go
> +func Post(requestUrl string, body interface{}, header http.Header, ctx context.Context) (*http.Response, http.Header, error) {
Yez

2024-08-23 00:45 UTC, EdWrld commented on services/api/middleware/idempotent.go
> +	return func(next echo.HandlerFunc) echo.HandlerFunc {
Nice catch !

2024-08-23 09:56 UTC, Cliftonz requested changes

2024-08-23 09:56 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +				idempotentUUID, err := uuid.Parse(key)
I do not think that this should be restricted like this a collision resistant key like UUIDv7, CUID, or ULID would work here. 

It's up the the client or our sdk to choose a quality key that they want to use based on there needs. This also could be different based on sdk too. 

I think it's best that we do not require this check

2024-08-23 09:56 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +	Processing IdempotencyStatus = "Processing"
This should be an enum not a set of constants

2024-08-23 09:56 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +					// If the request has already been processed return original response from nats
From the kv store, nats just happens to be the system we decided to use

2024-08-23 09:56 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +					if respErr != nil {
We should do more handling here, but I am unsure what the response is to handle it.

2024-08-23 15:15 UTC, EdWrld commented on services/api/middleware/idempotent.go
> +	Processing IdempotencyStatus = "Processing"
Go doesn't really have enums can you show me what you mean and why this doesn't suffice

2024-08-23 15:15 UTC, EdWrld commented on services/api/middleware/idempotent.go
> +				idempotentUUID, err := uuid.Parse(key)
Us not setting the standard for our api kind of makes me nervous, if this is removed then we won't be enforcing the use of any collision resistant key.

2024-08-23 15:15 UTC, EdWrld commented on services/api/middleware/idempotent.go
> +					if respErr != nil {
If this specific err is not nil its a issue with marshalling the struct. The CustomHttpErrorHandler will log the code and error

2024-08-23 18:43 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +	Processing IdempotencyStatus = "Processing"
I would do something like this that extends the enum to be able to be outputed as a string for readability.

https://blog.boot.dev/golang/golang-enum/#string-enums-in-go

its worth a discussion if this should be in our coding practices though

2024-08-23 23:24 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +				key := c.Request().Header.Get(IdempotencyKey)
I was looking at the PR that I worked on with Novu, and we did put in a check for 255 chars but I think this was to limit abuse and I do not remember the full reason why.

https://github.com/novuhq/novu/pull/4531/files#diff-c6b009a19009d025dcdb77bf3837d52b696de0bb84df0dd17e5ece0634e5f94dR51

thoughts?

2024-08-23 23:34 UTC, Cliftonz requested changes

2024-08-23 23:34 UTC, Cliftonz commented on services/api/middleware/idempotent.go
> +	IdempotencyKey = "Idempotency-Key"
We did forget two headers here
1. IDEMPOTENCY_REPLAY which is ture iff we are returning an idempotent response that has arleady been cached
2. RETRY_AFTER which specifies the amount of time to retry after if there is an error. for example 409 ocurres  while the request is processing and you should try it again to get the finished request

2024-08-23 23:34 UTC, Cliftonz commented on test/api/middleware/idempotency_test.go
> +func TestPostNewIdempotentItem(t *testing.T) {
I think for insurance we should implement a test that runs two concurrent requests with different keys and the same body to make sure that it returns two unique results

https://github.com/novuhq/novu/pull/4531/files#diff-d3566f70ba1a894fd57b1acc5aeebc03e224fcf9449e7c2803f816a09a733506R149

2024-08-23 23:34 UTC, Cliftonz commented
@EdWrld Great work on this, we are almost done

2024-08-29 00:11 UTC, Cliftonz commented
@EdWrld What is the update on this?

2024-08-31 17:08 UTC, EdWrld commented
Added abuse safety condition for idempotency keys, retry after header appears in response whenever an idempotent request is in progress, Idempotency replay header now appears on successful responses to inform client of whether response is cached or newly created. Created TestTwoDifferentKeysSameBodiesConcurrentRequests, previous tests have been updated to assert the existence of the new idempotent reply and retry after headers

2024-08-31 19:23 UTC, Cliftonz approved these changes
LGTM, did change the ReadAll method to another way that does not coopy to memory first and just streams it to the hash method.

2024-08-31 19:23 UTC, merged