Supertokens
autoscalerhq/Autoscaler pull request #15
Opened 2024-09-05 02:12 UTC by jasekiw

Add supertokens authentication to the system

2024-09-05 02:21 UTC, jasekiw commented
@Cliftonz Can you explain where the nextjs app and the go project went to? I'm having a hard time merging your changes in considering everything has been restructured.

2024-09-05 10:16 UTC, Cliftonz commented
@jasekiw website goes in the website folder and the go api goes in service/api.

I set the repository up based on golang monorepo standards. 

https://github.com/flowerinthenight/golang-monorepo

2024-09-12 01:50 UTC, jasekiw commented
@EdWrld @Cliftonz Ready for review

2024-09-12 12:10 UTC, Cliftonz requested changes
@jasekiw Great job on this! Just want to clarify somethings and make some changes.

2024-09-12 12:10 UTC, Cliftonz commented on website/src/api-client/ApiClient.ts
> +export class ApiClient {
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** What does this do?‏

2024-09-12 12:10 UTC, Cliftonz commented on website/src/api-client/NextjsApiClient.ts
> +export class NextJsApiClient {
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** What does this do?‏

2024-09-12 12:10 UTC, Cliftonz commented on website/src/app/(protected)/app/page.tsx
> +import {HomeComponent} from '~/components/auth/home';
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** What does the (protected) in the path do?‏

2024-09-12 15:53 UTC, jasekiw commented on CONTRIBUTING.md
> +# Contributing
In my experience automating documentation is usually lacking in real information. What do you mean here?

2024-09-12 15:55 UTC, jasekiw commented on CONTRIBUTING.md
> +* folders and files use lower case one word if possible, if not, use snake_case.
I have not seen use of kebab case for folders and files for go. I don't want to go against conventions here. I should clarify naming conventions for go vs nextjs however.

2024-09-12 15:59 UTC, jasekiw commented on services/api/middleware/middleware.go
> +	e.Use(IdempotencyMiddleware(nats.KeyValueStore, nats.Context))
ALL of these middleware apply to all requests, It's not a question of order but the route group. The protected route group are authenticated, everything else is not.

If you are saying that the login and register routes should not be idempotent, then I can change that too.

2024-09-12 16:00 UTC, jasekiw commented on website/src/app/(protected)/app/page.tsx
> +import {HomeComponent} from '~/components/auth/home';
It is a route group without affecting the url. It is useful for us to put all authenticated pages into without having to specify some wrapper since the layout handles authentication.

2024-09-12 16:00 UTC, jasekiw commented on website/src/api-client/NextjsApiClient.ts
> +export class NextJsApiClient {
This is the api client to call any nextjs api routes. We may not put any api routes in nextjs but I created in case we need to.

2024-09-12 16:01 UTC, jasekiw commented on services/api/main.go
> +		if err := e.Start(":4000"); err != nil && !errors.Is(err, http.ErrServerClosed) {
I can modify it back to 8888, It's just a variable change on the frontend. Once we have the env project finished, we can move it to environment variables.

2024-09-12 16:03 UTC, jasekiw commented on apps/web/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
I thought I deleted this section, It will be deleted. A push might have not made it up.

2024-09-12 19:08 UTC, Cliftonz commented on CONTRIBUTING.md
> +# Contributing
Not the documentation, but the process your detailing in the doc.

2024-09-12 19:30 UTC, Cliftonz commented on CONTRIBUTING.md
> +Run the backend go project
Basically we can automate this using "makefile" style approach with locally

2024-09-12 19:31 UTC, Cliftonz commented on CONTRIBUTING.md
> +* folders and files use lower case one word if possible, if not, use snake_case.
I am on board with this

2024-09-12 19:32 UTC, Cliftonz commented on services/api/main.go
> +		if err := e.Start(":4000"); err != nil && !errors.Is(err, http.ErrServerClosed) {
💯

2024-09-12 19:46 UTC, Cliftonz commented on services/api/middleware/middleware.go
> +	e.Use(IdempotencyMiddleware(nats.KeyValueStore, nats.Context))
Auth routes should not be idempotent, however, the auth-protected routes should be.

What I am getting at is that while they apply to all request orders do matter with the middleware.

2024-09-12 19:54 UTC, jasekiw commented on CONTRIBUTING.md
> +# Contributing
Oh for sure, having linting and code style settings in goland and webstorm would be best. Probably prettier for nextjs and we would need to find something for golang.

2024-09-12 22:36 UTC, jasekiw commented on services/api/main.go
> +type Environment struct {
This was a placeholder to consolidate env values until the env manager is made

2024-09-12 22:52 UTC, jasekiw commented on services/api/middleware/middleware.go
> +	e.Use(IdempotencyMiddleware(nats.KeyValueStore, nats.Context))
The middleware order matters if the middleware breaks the chain. CORS does not, but the supertokens just use middleware as a way to add their enpoints that break the chain and return a response.

I am going to assume the following results:

* All public routes should not have idempotency applied to them - the idempotency does not enable though unless the client passes an idempotency header so this is kind of mute in a normal since but I could see how an attacker could spam our idempotency key value store and cause problems. This could still happen with authenticated routes since it doesn't require much to create an account however we can at least block the user if it gets bad.

* rate limiting - should be global across all routes. This makes sense.

2024-09-12 23:01 UTC, jasekiw commented on CONTRIBUTING.md
> +Run the backend go project
@Cliftonz Can you make this adjustment in another PR? I am not familiar enough with this and it feels out of scope of the supertokens feature.

2024-09-12 23:25 UTC, Cliftonz commented on CONTRIBUTING.md
> +Run the backend go project
Good with me 🚀

2024-09-12 23:26 UTC, Cliftonz approved these changes
Lets 🚢

2024-09-12 23:26 UTC, merged